name: Print from file
on: push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3
        
      - name: Print hello_world.txt content
        run: echo "$(cat hello_world.txt)"
